server:
  host: 43.255.28.187
spring:
  application:
    name: shut-admin
  datasource:
    url: jdbc:mysql://43.255.28.187:3306/shut-prod
    username: root
    password: touzhen.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: testOneDB
      maximum-pool-size: 15
      max-lifetime: 180000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 5
      connection-test-query: SELECT 1
  redis:
    database: 6
    host: 43.255.28.187
    port: 6379
    timeout: 5000s  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
web:
  upload-path: /home/data/ # 文件存储位置



